### ISSUE TITLE
Deadline: 15 maggio ore 23.59 per creare la cartella vetrina

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/YouTrainer#3]
Ciao ragazzi, siete l'unico gruppo a non aver creato la cartella "vetrina". Perciò vi dò ancora tempo fino a stasera, dopo di che creerò il sito vetrina senza il vostro progetto!
Buona giornata
Teo

**Comment by andreamv** [comment]
Gentile Prof. Montanaro,
Grazie per averci ricordato la scadenza, la professoressa  Farinetti ci ha segnalato su sua richiesta di controllare le issues da lei inviate che purtroppo avevamo perso di vista. Essendo per oggi segnalate le due scadenze relative al caricamento di funzionalità  e del flow chart dell'architettura, abbiamo forse erroneamente considerato che anche la creazione del sito vetrina avesse scadenza nella giornata di oggi, prevedendo dunque di terminare tutto entro la lezione odierna. 
Comunque, come anticipato, abbiamo dato seguito questa mattina alle vostre richieste, dovrebbe trovare tutto caricato. Qualora dovessero verificarsi problematiche in merito alla documentazione sul sito vetrina terremo d'occhio le issues da lei inviate entro la giornata di oggi per potervi porre eventuale rimedio.
Un cordiale saluto,
YouTrainer's Team

**Comment by tmontanaro** [comment]
Ok, non vi preoccupate, anzi vi chiedo scusa: su github faccio poca attenzione al modo in cui scrivo i messaggi ed in effetti sono stato un po' troppo "incisivo" XD ... In effetti non vi avevo dato una deadline, vi avevo solo detto "il prima possibile" ... quindi scusate di nuovo: potevo essere più chiaro!
Il messaggio voleva essere diverso! Proprio perchè mancavate solo voi eravamo da un passo dall'avere tutto pronto per creare il sito vetrina, quindi valeva la pena invogliarvi a inserire quelle info quanto prima!
In ogni caso va bene così (cartella ha il nome giusto e il contenuto dei file va bene)!
Vi ringrazio per averle inserite e scusate di nuovo per il disguido ... devo stare più attento a quello che dico e scrivo ... XD
A giovedì!
Ps. Come vi dico sempre, per favore, datemi del tu, chiamatemi Teo e non mi chiamate prof! ;-)
